---
title: "Comandos  git"

output:
  html_document:
    toc: true
    theme: cosmo
---

###Idea
Estou tecleando un texto e non só quero gardalo senon que me fai ilusión ter nalgures as distintas versións que levo feitas, Pódoo gardar en plan *textoLuns1.doc*, *textoLuns1.doc*,*textoMartes.doc*,... ou usar un sistema que me automatice o que vou facendo. 

Sempre traballo na versión máis recente pero vou gardando as anteriores. O que quero chámase sistema de control de versións. Haino de varios tipos. Imos falar dun sistema de control de versións distriibuído chamado **git**.


Escribo nun ficheiro, fágolle un git, sigo traballando, fago outro git,... pero o mellor era a primeira versión...  dígolle que volva á primeira versión. Sigo traballando e de cando en vez fago outro git....

Podo subir este ficheiro coas súas versión á web (por exemplo github.com é grauíto)


###Comandos

**git add** engade un ficheiro á staging area (rocho onde se acumulan os ficheiros do que se quere gardar as versións )

**git reset**  saca o ficheiro desa staging area

**git commit** dá orde de considerar unha nova versión co que está na staging area

**git status** para ver como vai a cousa

**git log** para ver a lista de todas as miñas versións

**git push** sube as versións que estean listas ó repositorio na web



###Chuleta
Xeito rápido de facer versións dunha carpeta chea de ficheiros:

1. Entro en GitHub (xa teño aberta unha conta ,ou?)
2. Botón **New Repository** alá á dereita da páxina. Poño nome
3. Aló embaixo á dereita HTTP clone: copio o que  di (remate en xxxxx.git)
4. Vou no Terminal onde están os documentos que me interesa ter en git
5. ```git clone  xxxxxxxxxx.git```  Listo!!! nen git init nen caralladas
6. ```$ git add nomesFicheiros ```   (se tal     ```$git add --all```)
7. ```$ git commit -m 'Primeira vez'```
8. ```$ git push -u origin master```

Fago cambios e de cando en vez 
```
$ git add -u;git commit -m 'Outra vez'; git push origin master 
```




###Sitios a visitar

Web cunha especie de terminal interactiva. Moi básica 
https://try.github.io

Se queremos subir todo á web podemos usar:
 https://github.com
e ler todos os seus titoriais



 
